package com.ineedyourcode.decomposeme.domain

const val REQUEST_CODE_OK = 200
const val REQUEST_CODE_LOGIN_NOT_REGISTERED = 401
const val REQUEST_CODE_INVALID_PASSWORD = 403
const val REQUEST_CODE_LOGIN_REGISTERED_YET = 444
const val EXTRA_LOGIN_SUCCESS = "EXTRA_LOGIN_SUCCESS"